theme: jekyll-theme-minimal
title: Jacob Lahne (Assistant professor of food science, Virginia Tech) 
description: This is a page to provide access to projects, code, and interactive demos for code from Jacob Lahne's laboratory at Virginia Tech.
